#!/usr/bin/python
# -*- coding: utf-8 -*-

from sys import argv

script, filename = argv

print """
we're goign to erase %r
if you don't want that, hit ctrl-c
if you do want that, hit return 
""" % (filename)

raw_input("?")


print "opening file"
target = open(filename, 'w')

print "truncating the file. goodbye"
target.truncate()

line1 = raw_input("line 1:")
line2 = raw_input("line 2:")
line3 = raw_input("line 3:")

print "i'm going to write these to the file"

target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")

print "andfinally, we close it"
target.close()

